### ISSUE TITLE
Ensure as much of the app is case-insinsitive as possible

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#100]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/fcbfc37b-c518-438c-9a8b-d25918302edc)
In particular:
- "find" should be case-insensitive by default, since our "find" command is universal
- command keywords should be case insensitive
- Attribute names should be case insesitive
- Attribute values (strings) should follow the case being input, except during search

**Comment by Bandov** [comment]
i think attribute names are case insensitive except for those we implemented, but yes command keywords should be insensitive
