### ISSUE TITLE
Prevent window from being too small

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#118]
When window height is too small, there are graphical issues (pink box covers the title text)
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/3d34d2f3-7ca5-4ce5-9863-9b308440b540)
Empty contacts text is cut off
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/0d933c33-2adb-402c-b0be-e86b54dd7a34)

**Comment by DingBao-sys** [comment]
I think making it responsive abit too challenging

**Comment by ReflectiveObsidian** [comment]
Ok, then need to check the minimum screen size requirements of the tp and see if these issues appear at those sizes. Might be good to set minimum window size too, to prevent people from making the window too small and reporting it as a bug.

Sidenote:
Not allowed in v1.4:
any UI enhancements (even purely cosmetic enhancements e.g., alignments, style changes are not allowed)

**Comment by Bandov** [comment]
too big a bug to fix

**Comment by Bandov** [comment]
in the words of ding hao if i make a car to drive on land and you drive in the water is it my fault?

**Comment by ReflectiveObsidian** [comment]
Resizing limit works
