### ISSUE TITLE
Check error messages

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#142]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/0b64704f-bc5a-4c33-a0d4-328d2b8781c9)
should probably give error about wrong uuid first
to check: addrelation

**Comment by DingBao-sys** [comment]
because of the / parsing method, there is no way to identify which are the missing arguments

**Comment by ReflectiveObsidian** [comment]
addressed in #201
