### ISSUE TITLE
Possibly incomplete find feature

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#164]
since our find keyword is based on OR, meaning for the command

find A B
it returns any person with A or B, it means that when searching for anything like a name with multiple words, the user can never find just the person they are looking for

e.g. find David Sim
return: all david, and all sim

is this a not-meeting user needs issue?
possible solution would be to switch to find /key words 1 /key words 2
this will allow both OR and AND in find

**Comment by Bandov** [comment]
done
