### ISSUE TITLE
Improve anySearch command error messages

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#167]
Do these apply to familySearch as well?

Bugged error message:
(Image missing)

Would it be better to say that the uuid of these people are not found?
![319210906-432f5fb5-4d06-44c8-92fd-ddad07f4da45](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/86165878-d25a-47d4-88d9-3014e83c7ee5)

This message appears when the second uuid is correct. In this case its more accurate to say that there is missing uuid, OR quote the uuids being processed to make the issue clearer to the user. e.g. UUID does not exist ("")
![319211175-a6d38d5f-f136-4901-a81e-a07306d14c22](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/b2b49e06-4039-48be-a110-92af74a8984f)

**Comment by Emberlynn-Loo** [comment]
Not strictly incorrect, cannot change
