### ISSUE TITLE
Possible redundant mitigation code in MainWindow.java

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#190]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/ef2477a8-acdf-453e-ad6a-25b30e6670bb)
Result display is no longer used, so set accelerator may not be necessary.
But if we cant tell if it is still needed can ignore.

**Comment by DingBao-sys** [comment]
this is still needed cause the focus for this function is not specifically for ResultDisplay or CommandBox its to pass the key event around, so we still need it cause we still have elements that have controls
