### ISSUE TITLE
When user creates an attribute that is made up of numbers, it cannot be edited to become string (see comments)

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#193]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/664cfb29-cbd4-4720-9c9a-7bc766953909)
if this is intentional, make sure its in the UG, with justification. Otherwise just make them all strings, to be in line with "overzealous input validation"

**Comment by Bandov** [comment]
ok ive made it clear in the UG
