### ISSUE TITLE
[PE-D][Tester A] Ambiguity in finding out what UUID is

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-1/tp#211]
I know that `UUID` is a unique identifier to a person, but it does take me short while to figure out where exactly it is in the GUI interface. Finally I figured out because the example delete command has `0001` matches the sample person `Alex Yeoh`. Maybe if a screenshot of the GUI can be taken and then specify explicitly where `UUID` is shown. Then users can easily tell where `UUID` is.

![image.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/0588f51d-48af-4190-af46-f9535c82f681.png)

![image.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/305cbf23-c917-4b5b-99ac-0c8945febe91.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: JerryWang0000/ped#3

**Comment by ReflectiveObsidian** [comment]
We can make it clearer in the UG, or we can label the uuid in the UI.

**Comment by ReflectiveObsidian** [comment]
fixed alr
