### ISSUE TITLE
[PE-D][Tester E] Parsing error not caught

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#222]
## Describe the bug
Removing a space between attribute name and attribute value causes the first word of the value to be appended to the attribute name

## To Reproduce
add /namejohn doe

## Expected Behaviour
An exception should be thrown specifying invalid command

## Screenshots
![image.png](https://raw.githubusercontent.com/macareonie/ped/main/files/f131666d-ebf4-40b4-8357-abf95d5a792d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: macareonie/ped#3

**Comment by ReflectiveObsidian** [comment]
Command is valid. Update ug

**Comment by Bandov** [comment]
valid user defined issue update ug

**Comment by ReflectiveObsidian** [comment]
already fixed
