### ISSUE TITLE
[PE-D][Tester D] Unable to view relationships when there are too many relationships

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-1/tp#223]
## Description

When a person has too make relationships, unable to see all of the relationships.

## Example

Before:

![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/47d36718-925f-4ab2-983c-36d909f2e464.png)

After:

![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/a362515c-5ee2-4bf4-b7a0-1eea11c5cd0e.png)

After adding the `friends` relationship between them, the output says `Add Success`. However, unable to view the `friends` relationships as there are already existing relationships on the person.

## Fix

Upon further testing, I realised the relationship tags only appear upon the `list` command. I think would be good to show the relationship upon the `addRelation` command.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kwuunnn/ped#7

**Comment by ReflectiveObsidian** [comment]
Possible command not completing, or UI bug
