### ISSUE TITLE
[PE-D][Tester A] The Find person command performs better than the UserGuide claims

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#226]
The UserGuide says that only names are searched in the find command. However, I try to search with phone number but it also works.

![Screenshot 2024-04-05 164729.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/3508c680-374e-4105-a54c-01c58119d448.png)

![image.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/8a49945d-9f7c-49f7-bfca-a637934044d0.png)

If I search by `UUID`, it also works. It would be a pity not to mention that in UserGuide.

![image.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/8a1d9519-c997-482e-a851-41758cf3247b.png)

In the final example, I first add a person `John` with address `Alex`, and then try to `find /Alex`, 2 persons are listed. So I can assume that the real effect of `find` is to search by keyword.

![image.png](https://raw.githubusercontent.com/JerryWang0000/ped/main/files/2d9df766-279f-4e09-a90c-3034720b5ccf.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: JerryWang0000/ped#6

**Comment by Bandov** [comment]
update the UG to show my great command!

**Comment by ReflectiveObsidian** [comment]
addressed in #269
