### ISSUE TITLE
[PE-D][Tester C] Invalid Email

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#227]
Description:
When creating a person and adding the email to the person, the program doesn't check for '.com' or '@' and will accept an invalid string as the email.

Steps to Reproduce:

1. Navigate to the command box.
2. Enter add /Name Ananya Shahi /Email something
3. Click 'Enter'

Expected Behaviour:
The program should return an error saying that this is an invalid email, and valid emails end in '.com' and contain '@'

Actual Behavior:
The program successfully creates a new person but with an invalid email.

![invalid email.png](https://raw.githubusercontent.com/ananya21/ped/main/files/9e89661b-d884-437d-a971-d2a94c315a8b.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ananya21/ped#3

**Comment by Bandov** [comment]
not like the usual AB3, email is now user defined attribute and can contain any value

**Comment by ReflectiveObsidian** [comment]
already clarified that most attributes will not be checked
