### ISSUE TITLE
[PE-D][Tester D] Able to `addAttribute` when attribute already exists

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#232]
Attribute `Name` currently already exists as shown below:

![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/d9584a5b-f08e-4bd8-ba78-486d8e175cbb.png)

However, when adding an attribute that already exists, there is no error. An editAttribute is performed instead.

![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/a0b1ae97-23f8-4862-91b6-58229e19b737.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kwuunnn/ped#9

**Comment by ReflectiveObsidian** [comment]
Update ug?

**Comment by Bandov** [comment]
i think ill add a check if they try to add an attribute which already exists i wont let it

**Comment by Bandov** [comment]
fixed
