### ISSUE TITLE
[PE-D][Tester E] Incorrect addition of Birthday attribute with invalid Date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-1/tp#239]
## Describe the bug
Application succesfully adds an entry with invalid Date (year value) value

## To reproduce
addAttribute /[uuid here] /birthday 0000-10-10

## Expected Behaviour
Given the invalid year value, there should be an error message indicating said invalid input

## Screenshots

![image.png](https://raw.githubusercontent.com/macareonie/ped/main/files/039ac483-a22a-4c21-b7fc-33b2f0eafff6.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: macareonie/ped#6

**Comment by Bandov** [comment]
not going to fix as technically still valid and gene-nie ideally to be used as a family storage device as well

**Comment by Bandov** [comment]
add this to UG as well

**Comment by Bandov** [comment]
added
