### ISSUE TITLE
[PE-D][Tester B] Pre-defined sex attribute is listed as enum in user Guide but appears to accept any values

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-1/tp#240]
Entering a command to add the Sex attribute to a person with the value being a nonsense value still seems to be accepted, even though the User Guide lists the Sex attribute as being an enum. 
Command entered: 'addAttribute /0001 /Sex Abc'

![Screen Shot 2024-04-05 at 5.34.47 PM.png](https://raw.githubusercontent.com/S-Aishvarya/ped/main/files/167cd588-bddc-404f-b342-620c89f11faa.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: S-Aishvarya/ped#5

**Comment by ReflectiveObsidian** [comment]
To discuss

**Comment by Bandov** [comment]
i can fix it ah so that it only allows male or female

**Comment by ReflectiveObsidian** [comment]
ok, what values should the user input? (for UG)

**Comment by Bandov** [comment]
fixed
