### ISSUE TITLE
[PE-D][Tester D] Unable to add attribute if ATTRIBUTE_NAME contains a space

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#256]
## Example:

Input: `addAttribute /34aa /Full Name Ryan Ong`

![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/95f5bb35-a744-4cc8-a73e-4c59c2f5d33e.png)

## Fix

Perhaps you could explicitly state it in the UG.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kwuunnn/ped#12

**Comment by ReflectiveObsidian** [comment]
To update ug
