### ISSUE TITLE
[PE-D][Tester D] Unable to click hyperlink in Table of Contents

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-1/tp#262]
![image.png](https://raw.githubusercontent.com/kwuunnn/ped/main/files/dec3dfff-7534-4508-aa21-cc213c7eb913.png)

Unable to click hyperlink for ' Adding a person' and ' Locating persons by name'.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: kwuunnn/ped#18

**Comment by ReflectiveObsidian** [comment]
needs further investigation

**Comment by Bandov** [comment]
fixed...
