### ISSUE TITLE
ug - find will be moved into search results tab

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#272]

**Comment by ReflectiveObsidian** [comment]
this is no longer the case anymore, correct?

**Comment by Bandov** [comment]
do not do this and leave it to the future developments instead

**Comment by ReflectiveObsidian** [comment]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/c09e4abf-242e-44dd-809e-3d8456955e41)
