### ISSUE TITLE
Update ReadMe page & Update site-wide settings

### ISSUE THREAD

**Issue by Bandov** [AY2324S2-CS2103T-T11-1/tp#3]
Add a UI mockup of your intended final product. Note that the image of the UI should be docs/images/Ui.png so that it can be downloaded by our scripts. Limit the file to contain one screenshot/mockup only and ensure the new image is roughly the same height x width proportions as the original one. Reason: when we compile these images from all teams into one page ([example](https://nus-cs2103-ay2324s2.github.io/website/admin/teamList.html)), yours should not look out of place.

**Comment by ReflectiveObsidian** [comment]
As a potential user, I want to learn more about this product so that I can decide if it meets my needs.
