### ISSUE TITLE
To-dos for Developer Guide

### ISSUE THREAD

**Issue by Tsenrae** [AY2324S2-CS2103T-T11-1/tp#300]
### Design:
- Update UI component and diagrams
- For logic component,
	1. Currently relationship commands are under a separate package. Combine them together?
- For model component,
    - Maybe we shouldn’t put relationship package under person? The way the model is done, they’re technically separate

### Implementation:
- Each person needs to explain implementation of a feature (more than 1 page long) and supported by diagrams (see example in current DG: undo/redo feature)
- Split into these features
    - Add person
    - Delete person
    - Add attribute
    - Edit attribute
    - Find [keyword]
    - Add relation
    - Edit Relation
    - Delete relation
    - AnySearch
    - Clear
    - Deleteallpersons

### Appendix A: Requirements
- Update product scope, user stories, use cases, NFRs and glossary according to current implementation

### Appendix B: Instructions for manual testing
- Add step by step instructions to test the app manually (from launching all the way to saving)
- Include all added features

### Appendix C: Planned Enhancements
- Add bugs that can’t be fixed in v1.4 here (ie. feature flaws)
- Max of 10 enhancements (team size x2)

### Appendix D: Effort (OPTIONAL)
- Explain the difficulty level, challenges faced, effort required, and achievements of the project.
- Use AB3 as a reference point e.g., you can explain that while AB3 deals with only one entity type, your project was harder because it deals with multiple entity types.

**Comment by Bandov** [comment]
need do add person

**Comment by Bandov** [comment]
ive done 
Add attribute
Edit attribute
Find [keyword]
Delete attribute
Clear
Deleteallpersons
