### ISSUE TITLE
Deprecate outdated AB3 commands

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#47]
Exact list depends on which commands were edited and which were superseded.
Commands to check:
edit - superseded/edited due to attribute system?
find - superseded/edited due to attribute system?

**Comment by Bandov** [comment]
find needs to be superseded by the attribute system

**Comment by ReflectiveObsidian** [comment]
There are no more deprecated commands from AB3
