### ISSUE TITLE
Modify Design of Person Card

### ISSUE THREAD

**Issue by DingBao-sys** [AY2324S2-CS2103T-T11-1/tp#64]
- Create Hbox to hold Attribute type and value
- create a Box to hold all Attribute Descriptors 
- Change background colour of Person Card

**Comment by ReflectiveObsidian** [comment]
Would it be possible to split a person card into 2 columns, attributes on the left and first order attributes on the right?
I plan to implement this in #46.

**Comment by DingBao-sys** [comment]
Done

**Comment by DingBao-sys** [comment]
LGTM
