### ISSUE TITLE
As a new user, I can add detials about my relatives in JENGA... (Add attribute to people)

### ISSUE THREAD

**Issue by Bandov** [AY2324S2-CS2103T-T11-1/tp#8]
Feature allowing users to create and manage custom attributes, tailoring the organization of data to reflect unique family traits, relationships, or characteristics. This allows for users to optionally define and manage additional data fields with specific data types and behaviors.

**Comment by ReflectiveObsidian** [comment]
... so that I can keep track of who they are.
