### ISSUE TITLE
Should find command find by uuid as well?

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#82]
Currently, find command only searches attribute values. Do we want to return results where the end digits of the UUID matches? This could turn the find command into a universal search, finding matching UUID in addition to person's information.

**Comment by Bandov** [comment]
does this mean you want the find to find the UUID of a person as well. So for instance the if i find 1234 it returns the person with the uuid 1234?

**Comment by ReflectiveObsidian** [comment]
Yes
