### ISSUE TITLE
Address input validation

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#98]
![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/9b880b26-32d0-48e4-9c5d-ba35f59c8c13)
Whether some attributes currently have "Overzealous input validation" needs discussion. For example, phone number currently only allows integers.

**Comment by Bandov** [comment]
fix in the UG

**Comment by ReflectiveObsidian** [comment]
We should justify our validation by the fact that we allow arbitrary attributes
