### ISSUE TITLE
As an advanced user, I would like to have shortcuts to type my command more quickly.

### ISSUE THREAD

**Issue by ReflectiveObsidian** [AY2324S2-CS2103T-T11-1/tp#99]
Create case-insensitive aliases for commands.

![image](https://github.com/AY2324S2-CS2103T-T11-1/tp/assets/122241304/632312e1-93c1-4875-8587-d39198a5d044)

**Comment by Bandov** [comment]
for this i was thinking of doing like the first letters of each command word so for example find becomes f and findRelation becomes fr
